### ISSUE TITLE
Odd close behavior on mobile

### ISSUE THREAD

**Issue by dreg** [ItayXD/responsive-tooltip#5]
Thank you for the fantastic plugin, saved me a ton of time. Super minor but clicking on the tooltip pop-up didn't close it as expected. I changed line 75:

tooltip.bind( 'click', remove_tooltip);

to:

tooltip.bind( 'click', function(){ remove_tooltip(); });

and it's working as expected now. Worth a patch in the future or a migration from .bind() to .on()?

**Comment by ItayXD** [comment]
Thanks for noting! Would you mind creating a pull request with your fix? I
know it is very minor but I barely have time to work on it these days. I'll
be glad if I could just login and approve the request. Also if you see
anything else that needs to be fixed / changed please let me know.
Itay

**Comment by dreg** [comment]
Update code as pull request.
